version: "3"
services:
  vpn1:
    image: ghcr.io/bubuntux/nordvpn
    container_name: vpn1
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=email     # Required
      - PASS=password         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 5901:5900  # Recomended if using ipv4 only
    restart: always
  Spotify001:
    container_name: Spotify001
    privileged: true
    restart: always
    image: docker-spotify
    network_mode: service:vpn1
    environment:
      - VNC_PASSWORD=password
    depends_on:
      - vpn1